[package]
name = "workspacer"
version = "0.4.0"
edition = "2024"
license = "MIT"

[dependencies]
crossterm = { version = "0.29", features = ["events"]}
nucleo = { version = "0.5.0", default-features = false }
