name: Build and release

permissions:
  contents: write

on:
  push:
    tags:
      - "*"

env:
  CARGO_TERM_COLOR: always

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build release
        run: |
          cargo build --release
          mv target/release/workspacer .
          tar -czf workspacer.tar.gz workspacer LICENSE

      - name: Publish release
        uses: softprops/action-gh-release@v2
        with:
          files: workspacer.tar.gz
